title: Gottaprintem 3D Store
description: Tu tienda de impresión 3D de confianza – productos y calculadora de costos
theme: jekyll-theme-primer

markdown: kramdown

plugins:
  - jekyll-seo-tag

collections:
  products:
    output: true

sass:
  sass_dir: assets/css
  style: compressed
